name: Prueba

on:
  push:
    branches:
      - main

jobs:
  trabajo1:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "Hola mundo"

  trabajo2:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
  